apiVersion: v1
kind: Service
metadata:
  name: metacloud-api
  namespace: cnvrg-shim
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    app: metacloud-apiserver
